apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: omnibioai
spec:
  type: NodePort
  ports:
    - port: 11434
      targetPort: 11434
      nodePort: 31434
  selector:
    app: ollama

