apiVersion: v1
kind: Service
metadata:
  name: omnibioai-service
  namespace: omnibioai
spec:
  type: NodePort
  selector:
    app: omnibioai
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080

